config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :secrets, only: [:new, :create, :index]
  root to: "secrets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret.rb
class Secret < ApplicationRecord
  validates :title, :body, presence: true
  validates :title, :body, length: { minimum: 10 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :secrets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :set_secret, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create]

  # GET /secrets or /secrets.json
  def index
    @secrets = Secret.all
  end

  # GET /secrets/1 or /secrets/1.json

  # GET /secrets/new
  def new
    @secret = Secret.new
  end

  # GET /secrets/1/edit

  # POST /secrets or /secrets.json
  def create
    @secret = current_user.secrets.build(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to root_path, notice: 'Secret was successfully created.' }
        format.json { render :show, status: :created, location: @secret }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_secret
    @secret = Secret.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def secret_params
    params.require(:secret).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
              <p>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
              </p>
            <% else %>
            <p>
              <%= link_to 'Sign In', new_user_session_path%>
            </p>
						<p>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </p>
            <% end %>
    <%= yield %>
  </body>
</html>

app/views/secrets/_form.html.erb
<%= form_with(model: secret) do |form| %>
  <% if secret.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secret.errors.count, "error") %> prohibited this secret from being saved:</h2>

      <ul>
        <% secret.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secrets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Secrets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

        <% if user_signed_in? %>
        <th>Author</th>
        <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secrets.each do |secret| %>
      <tr>
        <td><%= secret.title %></td>
        <td><%= secret.body %></td>

        <% if user_signed_in? %>
        <td><%= secret.user.name %></td>
      </tr>
          <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secret', new_secret_path %>

app/views/secrets/new.html.erb
<h1>New Secret</h1>

<%= render 'form', secret: @secret %>

<%= link_to 'Back', secrets_path %>